#!/bin/bash                                                                                                                              
                                        
##SBATCH -D /home00/renep/RansPipe/cAL_MK_modNew
##SBATCH -J cAL_MK_modNew
##SBATCH --mem=64000 
##SBATCH --time=0-5:00:00
#SBATCH -n 4 
##SBATCH -N 1 
##SBATCH --exclusive   # use node(s) only for this job
##SBATCH --ntasks-per-node=4  # equally divide 96 cores in 4 chunks
##SBATCH -o slurm-%N-%j.out 
##SBATCH -e slurm-%N-%j.err
mpirun -np 4  ./forced_real_VF


